### ISSUE TITLE
Issue when running scalingo:mysql:backup_remote

### ISSUE THREAD

**Issue by yannski** [Scalingo/scalingo_databases_rake_tasks-gem#1]
```
$ bundle exec rake scalingo:mysql:backup_remote APP=XXXXX --trace
** Invoke scalingo:mysql:backup_remote (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute scalingo:mysql:backup_remote
rake aborted!
VariableError: VariableError
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/scalingo_databases_rake_tasks-gem-6f2b5adec1dd/lib/scalingo_databases_rake_tasks/tasks/common.rake:23:in `remote_credentials'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/scalingo_databases_rake_tasks-gem-6f2b5adec1dd/lib/scalingo_databases_rake_tasks/tasks/common.rake:61:in `open_tunnel'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/scalingo_databases_rake_tasks-gem-6f2b5adec1dd/lib/scalingo_databases_rake_tasks/tasks/mysql.rake:11:in `block (3 levels) in <top (required)>'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/yannski/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/yannski/.rbenv/versions/2.3.0/bin/rake:23:in `load'
/home/yannski/.rbenv/versions/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => scalingo:mysql:backup_remote
```

**Comment by yannski** [comment]
In fact, the app name provided on the commande line with APP= was wrong.
