### ISSUE TITLE
NameError: undefined local variable or method `pg_restore_after_9_4' for ScalingoPostgreSQL:Module

### ISSUE THREAD

**Issue by yannski** [Scalingo/scalingo_databases_rake_tasks-gem#3]
```
You're about to restore your remote database lesportecle_1946.
Data will be destroyed. (y/N) y
rake aborted!
NameError: undefined local variable or method `pg_restore_after_9_4' for ScalingoPostgreSQL:Module
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/scalingo_databases_rake_tasks-gem-81229906bc98/lib/scalingo_databases_rake_tasks/tasks/postgresql.rake:81:in `restore'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/scalingo_databases_rake_tasks-gem-81229906bc98/lib/scalingo_databases_rake_tasks/tasks/postgresql.rake:26:in `block (4 levels) in <top (required)>'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/scalingo_databases_rake_tasks-gem-81229906bc98/lib/scalingo_databases_rake_tasks/tasks/common.rake:86:in `open_tunnel'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/scalingo_databases_rake_tasks-gem-81229906bc98/lib/scalingo_databases_rake_tasks/tasks/postgresql.rake:24:in `block (3 levels) in <top (required)>'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/yannski/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/yannski/.rbenv/versions/2.1.2/bin/rake:23:in `load'
/home/yannski/.rbenv/versions/2.1.2/bin/rake:23:in `<main>'
Tasks: TOP => scalingo:postgresql:restore_remote
```

**Comment by whollacsek** [comment]
fixed in 283f215e4c616dfa34bb3991c4321d1f7954b8e1
